### ISSUE TITLE
Issue with eliding and ProdMode

### ISSUE THREAD

**Issue by n3ziniuka5** [japgolly/scalacss#104]
I am having some issues with eliding and cannot enable Prod mode.

in my build.sbt I have:
```scala
scalacOptions ++= Seq(
  "-deprecation",
  "-encoding", "UTF-8",
  "-feature",
  "-language:existentials",
  "-language:higherKinds",
  "-language:implicitConversions", 
  "-unchecked",
  "-Xfatal-warnings",
  "-Xlint",
  "-Yno-adapted-args",
  "-Ywarn-dead-code",
  "-Ywarn-numeric-widen",
  "-Ywarn-value-discard",
  "-Xfuture",
  "-Ywarn-unused-import",
  "-Xelide-below", "OFF"
)
```

In my code I always do `import scalacss.Defaults._`, but I noticed that my CSS is not minified. I tried to debug the issue and tried to print out this:
```scala
dom.console.log(scalacss.internal.Platform.DevMode)
dom.console.log(scalacss.defaults.DefaultSettings.instance.toString)
```
which prints:
```
false
scalacss.defaults.DefaultSettings$Dev$@1
```

It is very strange as it seems that eliding did work for the first statement, but not for the second. I suspect this is because I am calling the method with `@elidable` directly from my code which is then compiled with `-Xelide-below OFF`, but `scalacss.defaults.DefaultSettings.instance` is already compiled and was compile without `-Xelide-below OFF`.

**Comment by japgolly** [comment]
Hi @n3ziniuka5 . Which version of Scala were you using?

**Comment by n3ziniuka5** [comment]
2.11.8

**Comment by japgolly** [comment]
Confirmed, test case added, and fixed on master.
