### ISSUE TITLE
Help needed wrt <less> compiler.

### ISSUE THREAD

**Issue by abhi18av** [japgolly/scalacss#116]
Hi @japgolly 

I've been trying hard to get into the isomorphic world of Scala(JS),  especially through the wonderful `spa-scalajs-tutorial` by `ochrons` but I keep running into errors trying to get it working on my main `macOS` machine.

The error message is dumped only once I open up the browser and, it's narrowed down to `lessc` and by extension to this plugin.

Could you please ( please!) help me out on this one?

https://github.com/ochrons/scalajs-spa-tutorial/issues/67

**Comment by abhi18av** [comment]
Adding the screenshot for better comprehension.

<img width="1440" alt="screen shot 2017-06-14 at 19 16 25" src="https://user-images.githubusercontent.com/12799326/27135593-897cb448-5136-11e7-844c-4a015ec34f7c.png">

**Comment by japgolly** [comment]
Hi @abhi18av , this doesn't use Less. I don't think the problem you're having relates to this library.

**Comment by abhi18av** [comment]
@japgolly, oh okay.

In that case, please do feel free to close the issue. 

Is there a way I could correctly make the SPA run on the macOS machine, what are your suggestions ?

**Comment by abhi18av** [comment]
The solution has been that the `sbt-less` version needed to be updated to `1.1.0` ( with last commit in 2015(!).

I've outlined the solution in the original issue as well.
