### ISSUE TITLE
Defining and applying styleAs on the fly?

### ISSUE THREAD

**Issue by Unmoving** [japgolly/scalacss#118]
Consider this:
```
object TestCss extends StyleSheet.Inline
{
  import dsl._

  val testBackground = bg("awesome-background", "https://placehold.it/2000x2000")

  def bg(className: String, imgUrl: String) = style(
    addClassName(className),
    backgroundImage := s"url($imgUrl)"
  )
}
```
Somewhere else:

```
html(
    ...
    section(TestCss.testBackground, "Testing the background")...
)
```

This works like a charm

But what about a little more dynamic backgrounds?

```
  val otherBackground = TestCss.bg("another-one", "http://url-to-awesome-image")
    ...
    section(otherBackground, "Testing the background")
```

Sadly this does not work.

I guess it's because of some magic going on in `StyleSheet.Inline`... but, can I somehow get this working easily? Am I missing something?

What I basically want is to dynamically generate the `StyleA` and apply it. Although `otherBackground` is indeed a `StyleA` the rendered html looks like this:

`<section class="TestCss-bg-2 another-one">Testing the background</section>` and neither `TestCss-bg-2` nor `another-one` are actually a style applied

Maybe this isn't even valid at all and not possible in ScalaCSS. I merely thought I'd ask before dying dumb.

**Comment by japgolly** [comment]
Hi @Unmoving, no ScalaCss doesn't support on-the-fly styles. The stylesheet needs to be closed. You can still have dynamic styles so long as they're total and deterministic, see http://japgolly.github.io/scalacss/book/features/stylef.html
