### ISSUE TITLE
Version in sbt snippet in quickstart book is an out of date version which does not compile with scalajs-react

### ISSUE THREAD

**Issue by cfraz89** [japgolly/scalacss#119]
The quickstart at the [quickstart](https://japgolly.github.io/scalacss/book/quickstart/index.html) refers to version 0.5.1 of scalacss, of which ext-react does not compile against latest scalajs-react.

This should probably be updated to 0.5.3, as it can throw new users.

**Comment by japgolly** [comment]
True that, thanks.

Fixed in 61755044951549ca82df9d5d8b9a2ec5614ef396
