### ISSUE TITLE
Using scalacss in server code - solving issues with Content Security Policy

### ISSUE THREAD

**Issue by kszilagyi** [japgolly/scalacss#123]
Hi,

I find this library is really great, I really like the type safeness of the inline style. But my browser(Chrome) refuses to apply the inline style because it violates the Content Security Policy. Which is fair, as it's not very secure. 

I didn't want to add a security exception and I didn't want to go to the standalone style as it looks way less type safe so I thought I could have the style object in the server(shared with the js code) and output it from an endpoint (runtime doing something like returning MyStyle.toString) while have it referenced from the Js.

I think this would work but unfortunately there is no JVM build of the library as far as I can tell. Is there any reason to not have one? Or do you have a recommended way to solve this issue?

Many thanks,
Kristof

**Comment by japgolly** [comment]
Hi, this library is published for JVM as well. If you add it to your JVM
project's dependencies it should just work. If it doesn't try changing %%%
in the library declaration to %%.

**Comment by kszilagyi** [comment]
Hi,

Thanks for the quick reply. Yeah, you are right, my bad. I tried to use "com.github.japgolly.scalacss" %%% "ext-react" in the server which really doesn't have jvm port but obviously that's not what I need. So when trying core instead it worked.

I will close the issue, thanks for the help!

**Comment by japgolly** [comment]
Great to hear & no worries!
