### ISSUE TITLE
 could not find implicit value for evidence parameter of type scalacss.internal.StyleLookup

### ISSUE THREAD

**Issue by vangogh500** [japgolly/scalacss#136]
sealed trait Color {
    val value: scalacss.internal.Macros.Color
  }
  case object PrimaryColor extends Color {
    val value = c"#0D0C1D"
  }
  case object SecondaryColor extends Color {
    val value = c"#474973"
  }
  case object TernaryColor extends Color {
    val value = c"#474973"
  }

  val domain = Domain.ofValues(PrimaryColor, SecondaryColor, TernaryColor)

  val bg = styleF(domain)(color => styleS(
    backgroundColor(color.value)
  ))

could not find implicit value for evidence parameter of type scalacss.internal.StyleLookup[Product with Serializable with vangogh500.lolstats.style.Coloring.Color]
[error] Error occurred in an application involving default arguments.
[error]   val bg = styleF(domain)(color => styleS(
[error]                          ^
[error] one error found
[error] (client/compile:compileIncremental) Compilation failed
[error] Total time: 0 s, completed Jun 24, 2018 3:54:51 AM

**Comment by vangogh500** [comment]
Explicitly stating the type of the domain fixed the issue. Going to close the thread. Thanks for the help :)

`private val domain = Domain.ofValues[AppColor](FacebookBlue, Cinnabar, DeepSkyBlue)`

**Comment by japgolly** [comment]
Oh of course, that makes sense knowing how Scala LUBs. That would've been frustrating but I'm glad you figured it out.
