### ISSUE TITLE
`gap` and `row-gap` attrs aren't supported

### ISSUE THREAD

**Issue by teozkr** [japgolly/scalacss#139]
`column-gap` is, but only because it existed before CSS Grids (as part of CSS Multi-Column Layouts).

**Comment by japgolly** [comment]
Closed via #140

**Comment by teozkr** [comment]
Great, thanks!

**Comment by teozkr** [comment]
By the way, GH will automatically close the issue when the PR is merged if the commit message (or PR message body) contains `Closes #139`.
