### ISSUE TITLE
Scala 2.13

### ISSUE THREAD

**Issue by calvinmo** [japgolly/scalacss#153]
I am sure I am not the first person to ask this.  Do you have plans to upgrade to Scala 2.13?

If I'm not mistaken scalajs is holding you back.  Are there any other dependencies that are problematic in this regard?

**Comment by japgolly** [comment]
Hi. Yeah Scala.js is ok but this is being held up by scalajs-react which is
being held up by monocle-cats.

**Comment by calvinmo** [comment]
That is unfortunate.  I will be watching progress up the chain of dependencies with interest.  Please close this issue if you would like to tidy up.  Otherwise you can leave it open for others interested in the same problem.

**Comment by japgolly** [comment]
0.6.0-RC1 is on its way to Maven Central with support for Scala 2.13

**Comment by calvinmo** [comment]
Excellent - thank you - what is the timeframe we have for testing before your release 0.6.0?

**Comment by japgolly** [comment]
You're welcome :)

Probably around 2 weeks.

**Comment by calvinmo** [comment]
Excellent - that is enough.

**Comment by calvinmo** [comment]
I have tested `0.6.0-RC1` and it works well.  The only issue I cannot resolve is syntax highlighting in IntelliJ (see below).  It seems the Intellisense is not able to resolve certain parts of scalacss `Attrs`.  As a workaround I have imported `scalacss.internal.Attrs` directly and used it as in line 1.  However, I suspect you do not consider this to be part of the interface so its subject to internal modifications at your leisure and hence could break at any point.

I suspect this is not so much a scalacss issue as it is an edge case for IntelliJ Intellisense.  If you can't suggest any alternatives I intend to open an issue with Idea.

![image](https://user-images.githubusercontent.com/11868592/64611021-c3042d80-d3d0-11e9-913e-ae80e0fc1a4a.png)

**Comment by vmchura** [comment]
Hi, @calvinmo did you found another way to work properly on IntellIJ without those red marks?
It compiles fine, but is quite hard to code having red marks everywhere.

**Comment by calvinmo** [comment]
No luck in this regard - I have just done as follows - which is a hack at best - notice the extra seemingly unnecessary imports:

![image](https://user-images.githubusercontent.com/11868592/77518982-5ab9fc80-6e87-11ea-884d-266003511339.png)
