### ISSUE TITLE
Media query is sorted wrong

### ISSUE THREAD

**Issue by FabioPinheiro** [japgolly/scalacss#228]
In a `StyleSheet.Inline`I have
```scala
val xs = media.minWidth(0.px)
val sm = media.minWidth(576.px) // Small devices (landscape phones, 576px and up)
val md = media.minWidth(768.px) // Medium devices (tablets, 768px and up)
val lg = media.minWidth(992.px) // Large devices (desktops, 992px and up)
val xl = media.minWidth(1200.px) // Extra large devices (large desktops, 1200px and up)
...
```
Everything works fine and very responsive until I get to `xl`
After debugging I can see the order is sorted wrong
```
@media (min-width:0) {...}
@media (min-width:1200px) {...}
@media (min-width:576px {...}
@media (min-width:768px) {...}
@media (min-width:992px) {...}
```

**Comment by FabioPinheiro** [comment]
@japgolly Can you point me in the right direction
Can we fix it here or is not related?
https://github.com/japgolly/scalacss/blob/master/core/shared/src/main/scala/scalacss/internal/Cond.scala#L57

**Comment by japgolly** [comment]
Oh my, I completely forgot to respond to this, I'm so sorry @FabioPinheiro . Yes I believe that's exactly the place to fix it. I'd also recommend adding your exact example as a test case to `InlineTest.scala`.

**Comment by FabioPinheiro** [comment]
Now is I who is sorry for not replying. The last couple of months was not easy for me.
But now I'm 100% invested in trying to transform my pet project into job.
I want to see this fixed. I think there are more ordering problems when I use the media query in multiple places.
