### ISSUE TITLE
Use official Scala.JS build of Shapeless (when available)

### ISSUE THREAD

**Issue by antonkulaga** [japgolly/scalacss#23]
There are two scalajs forks of shapeless: yours and @alexander-myltsev 's ( https://github.com/alexander-myltsev/shapeless ). As I use both parboiled and scalacss,so I have to decide which shapeless scalajs fork I should use. Could you discuss with @alexander-myltsev and choose scalajs shapeless fork that will be the main one?

**Comment by japgolly** [comment]
I don't mind who does the forking, but this is matters to me:

1. Fork should be on maven central. I don't want to add special resolvers.
2. New forks should be published immediately when a new version of Shapeless is out.

For those reasons I started maintaining my own fork. It's no big deal. In fact as a workaround, you can exclude whichever fork you like in your build pretty easily (see: [SBT: Excluding Transitive Dependencies](http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies)).

**Comment by japgolly** [comment]
Closed via 5c66011

**Comment by antonkulaga** [comment]
Coul you publish it? I would like to update to scalacss with dependency from official build of shapeless

**Comment by japgolly** [comment]
When the next release is ready, sure. Will be before the end of the month at the latest.
