### ISSUE TITLE
Compose only checks CSS name, not name + value for conflicts

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalacss#28]
Given the following styles:

```
  val styleA = style(
    display.block
  )

  val styleB = style(
    display.block,
    styleA
  )
```
The console emits the following warning:

 // [CSS WARNING] .scalacss-0002 -- display overridden by display."

Since both 'display' keys have the same value 'block' there really shouldn't be a warning.  Ideally the conflict checker should compare both attribute AND value.  And display the conflicting value in the string (in addition to key name).  For example, the following code:

```
  val styleA = style(
    display.block
  )

  val styleB = style(
    display.flex,
    styleA
  )
```
should generate a warning:

 // [CSS WARNING] .scalacss-0002 -- 'display: block' overridden by 'display: flex'."

**Comment by japgolly** [comment]
Done. Non-conflicting values are ignored; conflicts produce warns like this:
```
[CSS WARNING] .DefaultsTest_Dev_SS-0001 -- {margin-left: 6px} conflicts with {margin: 12px}
[CSS WARNING] .DefaultsTest_Dev_SS-0002 -- {cursor: zoom-in} conflicts with {cursor: pointer}
```
