### ISSUE TITLE
Make CSS classname match variable name (in dev-mode)

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalacss#35]
So
```scala
val abc = style(display.block)
```
would automatically become
```scala
val abc = style("abc")(display.block)
```

**Comment by antonkulaga** [comment]
If it is possible and if it can be generalized, it would be useful for many libs.

**Comment by japgolly** [comment]
10:30pm Start. 3:30am :tired_face: I've *"learnt"* macros and got this working for style & styleF.

Next version will be 0.3.0 and will include this. Usage and result looks quite nice. 

TODO:
* Revise doco - code snippets, generated CSS.
* Document new setting is `Defaults`.

**Comment by japgolly** [comment]
@antonkulaga Not possible I don't think. You can't even add one step of separation. In terms of generalisation, I think the best that could be done would be a `def auto: String` macro which would give you:
```scala
def hello(name: String) = ()

val abc = hello(auto)
// macro would translate ↑ to ↓
val abc = hello("abc")

// I was hoping this would work but it doesn't.
def helloFail(name: String = auto) = ()
```

**Comment by japgolly** [comment]
To be clear, in this library `style` and `styleF` will be macros - there won't be a need to type `auto` everywhere. So:

```scala
val abc = style(display.block)

val hasError =
  styleF.bool(ok => styleS(
    backgroundColor(if (ok) green else red)))
```

would result in

```css
.abc        { display: block }
.hasError-t { background-color: green }
.hasError-f { background-color: red }
```

**Comment by chandu0101** [comment]
> 10:30pm Start. 3:30am
wow it indeed happened  in overnight! , thanks for your hard work mate :) :+1:

**Comment by japgolly** [comment]
Thanks mate :grinning: But nah, I'm not that good. I also had to spend 7am~9am this morning on it cleaning it all up, hehe. Now I'm looking at the clock thinking jeez I've got a whole day of very different coding I need to do. :S

**Comment by enijns** [comment]
I also took a stab at this one (didn't expect you to tackle this so quickly :+1:).

For me it's mostly an experiment with macros. I didn't integrate it deeply into the library and just added an extra method to work around overload issues. In case you wanted to compare approaches here's my take: https://github.com/enijns/scalacss/commit/16696f3dd5092c400eea6bf0d0fbd8a578f11f36

One thing I did was to use the fullname of the val instead of the short local name - this could be a way to enforce unique (albeit long) names. In the unit test I end up with the following css class name:
```css
scalacss_AutoNameTest_Issue35_SampleStyles_other
```

**Comment by japgolly** [comment]
Hey @enijns I'm just about to clock off for the day, very tired of looking at monitors so I'll have a look at your commit another day, but for now: Thanks! I've known macros for less than 24hrs so I'm sure I'll learn something looking at what you've done. I've also pushed [my macro branch](https://github.com/japgolly/scalacss/tree/macros) for now in case you want to have a look at my attempt. Anyway, talk properly later, cheers & bye for now

**Comment by japgolly** [comment]
Wow that'd would've been really cool @enijns, thanks anyway. Unfortunate timing. I learned from looking at your example - I thought quasiquotes were provided by macro paradise but you're using them without it. You also figured out how to use varargs with macros - that's good to know cos I played around with that a bit but didn't get it.

I'm gonna stick with using `name`  instead of `fullName` because it gets prepended with the `classNameHint` of the stylesheet (which is its classname by default). It gives users the control to change it or turn it off as they need.

**Comment by japgolly** [comment]
Done.

**Comment by enijns** [comment]
@japgolly great to see this is resolved. I'm not too familiar with scalacss yet, but the classNameHint looks more flexible indeed.

PS: quasiquotes are in scala 2.11 as far as I know - and since you're not targeting scala 2.10 it's possible to use them
