### ISSUE TITLE
borderBottomColor (and possibly others) not accepting string color

### ISSUE THREAD

**Issue by cretz** [japgolly/scalacss#42]
When attempting something like ``borderBottom(1 px, solid, "#eee")`` in a standalone sheet, I get the following error whereas ``borderBottomColor("#eee")`` works.

    diverging implicit expansion for type scalacss.ValueT.==>[String,B]
    starting with method ruleChain in class Rules
        borderBottom(1 px, solid, "#eee")

I saw 94249991af2ea011e580999b3efe23ec14d33581 and I see that I can do ``borderBottom(1 px, solid, Color("#eee"))`` (but sadly I have to manually import scalacss.Color though I know I could use rgb in ColorOps). Is this limitation by intention? If so it might be worth mentioning in the guide if not already present (I could not find it).

**Comment by japgolly** [comment]
What about ↓?
```scala
borderBottom(1 px, solid, "#eee".color)
```

**Comment by japgolly** [comment]
Colour literals are a bit of a question mark atm. In places like `borderBottomColor` it's unambiguous, so it accepts both `Color` and `String`. In other locations that need typed values, it's required to add `.color` to colour literals to (from memory) differentiate from other typed values.

I'm not really happy about that situation. I'd like to improve it at some point.

**Comment by cretz** [comment]
I apologize for not testing it, I have been busy and this is a side project. I assume it will work, just thought you might want to document this somewhere.

**Comment by japgolly** [comment]
np at all and yes, I will indeed document this before the next release :) Cheers

**Comment by cretz** [comment]
Confirmed ``.color `` works fine.

**Comment by japgolly** [comment]
Good to hear. I'll keep this open though so I remember to update the doco

**Comment by japgolly** [comment]
Done in a147bc17b03ef8902acc103011cdebbd4319eb55
