### ISSUE TITLE
Reuse style tags  - GlobalRegistry.onRegistration(_.addToDocument())

### ISSUE THREAD

**Issue by chandu0101** [japgolly/scalacss#43]
```scala
 GlobalRegistry.register(
      GlobalStyle,
      NavMenu.Style,
    HomePage.Style)
    GlobalRegistry.onRegistration(_.addToDocument())
```
currently its creating new style tag for every new registration 

it looks like there is constrain on number of style tags 

> IE. :) They had a limit on 31 stylesheets at one point, and a max limit on the number of selectors allowed in a stylesheet. If you imported things with @ import you could only do so 31 at a time per level or something.
 I have hit that limit before, in a framework that pretty much gave every component/widget its own stylesheet and some of those created their own dynamic style tags on the fly.
<AMcBain> We ended up cheating by sharing the same dynamic style tag across all that needed it.
<AMcBain> Version 3 of the framework changed approaches so we're not even close to the limit anymore.

It would be cool if we reuse style tags instead of creating new ones!

**Comment by japgolly** [comment]
Of course IE is the one with the problem. :neutral_face: Ok, this shouldn't be a problem to change.

**Comment by japgolly** [comment]
Done. Replace
```scala
GlobalRegistry.onRegistration(_.addToDocument())
```
with
```scala
GlobalRegistry.addToDocumentOnRegistration()
```

**Comment by chandu0101** [comment]
wow , cool thanks mate :)  . Hope you'll be blessed with macro magic overnight , yeah one more #35 :p ;)

**Comment by japgolly** [comment]
no worries :) Yeah #35 would be awesome. I was thinking of playing around with macros or scalameta (the future of macros) this weekend but I've had enough of coding. 7 days a week for months is not smart. Maybe next weekend

**Comment by chandu0101** [comment]
>Maybe next weekend

yay , it should be in next release then! ,hope :)
