### ISSUE TITLE
Psuedoclasses don't mix well with unsafeChild

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalacss#59]
I have the following ScalaCSS.  I'm trying to change the style of 'inner' when 'outerStyle' is hovered on.

```
  val outerStyle = style(
    cursor.none,

    &.hover(
      cursor.pointer,
      unsafeChild("inner") {
        display.block
      }
    )
  )
```

  // I thought this would generate:

```
  .outerStyle {
    cursor: none;
  }
  
  .outerStyle:hover {
    cursor: pointer;
  }
  
  .outerStyle:hover .inner {
    display: block;
  }
```

  // But instead it generates the hover on the .innner:
  
```
  .outerStyle {
    cursor: none;
  }
  
  .outerStyle:hover .inner {
    cursor: pointer;
  }
  
  // Note the hover is moved onto the .inner unsafeChild instead of on .outerStyle
  .outerStyle .inner:hover {
    display: block;
  }
```

What's interesting is the cursor style does get applied in the right place.  The same `hover` condition is treated differently whether there is a unsafeChild mixed in.

**Comment by Starzu** [comment]
https://github.com/AVSystem/scalacss/commit/5328dbb815922fadb3cdd127bc13b9e6caf8f27e - probably it's solution of described problem.

**Comment by japgolly** [comment]
#68 fixes this
