### ISSUE TITLE
License discrepency

### ISSUE THREAD

**Issue by matthughes** [japgolly/scalacss#60]
The project metadata in Build.scala reports LGPL, but your LICENSE file reports Apache 2.0.  Can we fix the former to point to http://www.apache.org/licenses/LICENSE-2.0 assuming that is your intent?  My projects use the metadata in SBT to compute open source attributions.

**Comment by japgolly** [comment]
I'll have to re-read both licences. I never seem to remember licence stuff.

**Comment by matthughes** [comment]
FWIW You have Apache 2.0 in both Build and LICENSE for scalajs-react.

**Comment by japgolly** [comment]
Closed via e7d6fd8185d4990662fd8e6e24fcd09cf15e2304
