### ISSUE TITLE
How do you use svg in standalone mode?

### ISSUE THREAD

**Issue by hntd187** [japgolly/scalacss#77]
I for the life of me cannot figure out how to emulate the CSS in this example here. 

https://bl.ocks.org/mbostock/3048450

```
object Style extends StyleSheet.Standalone {
  import dsl._
  "body" -(
    backgroundColor.white,
    color.black,
    fontSize(10px)
    )
  ".bar" -(
    &("rect") -(),
    &("text") -()
    )
  ".axis" -(
    &("path") -(
      svgStroke.black),
    &("line") -(
        svgStroke.black)
    )
  val css = d3Style.render
}
```

Am I missing something in the documentation? I see the svg attrs, but I can't figure out how to actually use their syntax correctly, they seem to be left out of the DSL or used in some different sense. Am I crazy or just missing something?

**Comment by japgolly** [comment]
Adding auto-complete for all attributes is an ongoing process as it's not always easy. If an attribute is "untyped", you just use `attr := value`, for example:

```scala
  ".bar" - (
    &("rect") - (
      svgFill := "steelblue",
      svgShapeRendering := "crispEdges"
      ),
```
