### ISSUE TITLE
"Failed to deserialize info of file compiled with Scala.js 0.6.6"

### ISSUE THREAD

**Issue by AIMMOTH** [japgolly/scalacss#78]
Using import

libraryDependencies += "com.github.japgolly.scalacss" %%% "core" % "0.4.0"

Fails with $ sbt fastOptJS

[error] (compile:fastOptJS) org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 0.6.6 (supported: 0.6.0, 0.6.3, 0.6.4, 0.6.5): C:\Users\Carl\.ivy2\cache\com.github.japgolly.scalacss\core_sjs0.6_2.11\jars\core_sjs0.6_2.11-0.4.0.jar#scalacss/DslMacros$MStyleF$class.sjsir

**Comment by japgolly** [comment]
It looks like you're using Scala.JS version 0.6.5. Try updating your `plugins.sbt` to use 0.6.6 or 0.6.7.
