### ISSUE TITLE
Keyframes only support Int percentages

### ISSUE THREAD

**Issue by turbolent** [japgolly/scalacss#90]
It looks like keyframes only support integer percentages, even though float percentages should be supported. https://github.com/japgolly/scalacss/blob/64af84ccdaa5df697e6cc9a2098a97a79650c7ff/core/shared/src/main/scala/scalacss/internal/Dsl.scala#L270

If confirmed I'm happy to open a PR to fix this.

**Comment by japgolly** [comment]
Ah, you're totally right, I can't see why decimals shouldn't be allowed there. A PR would be welcome. :)

**Comment by japgolly** [comment]
Closed via 74d9cc100387cad83fc87cabb7b2089705800498
