### ISSUE TITLE
 unary_- is missing on Length

### ISSUE THREAD

**Issue by MasseGuillaume** [japgolly/scalacss#93]
`padding(-14.px)`

**Comment by japgolly** [comment]
Would be good to fix this. In fact, this would be a tiny PR if you're interested.

As a workaround, you can currently do this:
```scala
padding(-14 px)
```

**Comment by MasseGuillaume** [comment]
hey @japgolly Unfortunately, I had to give scalacss.

I had existing less and I was not able to convert some selectors in Standalone mode:

```less
x {
  y, z {
   k: y;
  }
}
```

**Comment by japgolly** [comment]
No worries @MasseGuillaume . That syntax should work but honestly, I'm not sure how much value there is in standalone mode. Inline mode is where this library becomes exponentially awesome, one of the most simple reasons is that your css is always linked to your usage at compile-time so it always works (not stringly-typed), it's really easy and safe to refactor and see what's used where etc.

**Comment by MasseGuillaume** [comment]
@japgolly yeah I know inline mode is really helpful. Concretely I want to style codemirror, it's created by javascript code in a separate library, this is why I need a good standalone mode.

**Comment by japgolly** [comment]
@MasseGuillaume Ah I understand.

**Comment by japgolly** [comment]
Added in 9f4fd802b6e57c76169b38db885344bca97b2947.
