### ISSUE TITLE
Broken links in gitbook

### ISSUE THREAD

**Issue by Risto-Stevcev** [japgolly/scalacss#99]
The "Full examples" section in https://japgolly.github.io/scalacss/book/features/basics.html returns 404 for the links:

https://github.com/japgolly/scalacss/blob/master/core/src/test/scala/scalacss/full/StandaloneTest.scala
https://github.com/japgolly/scalacss/blob/master/core/src/test/scala/scalacss/full/InlineTest.scala

**Comment by japgolly** [comment]
Thanks. The links had been changed on master but not published to gh-pages. Should be fixed now.
